name: flexi_editor
description: "Flexible Editor for Flutter"
version: 1.0.0
homepage: https://github.com/scadasystems
repository: https://github.com/scadasystems/flexi_editor

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  defer_pointer: ^0.0.2
  provider: ^6.1.5+1
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter: